/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_faendir_zachtronics_bot_om_JNISolutionVerifier */

#ifndef _Included_com_faendir_zachtronics_bot_om_JNISolutionVerifier
#define _Included_com_faendir_zachtronics_bot_om_JNISolutionVerifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faendir_zachtronics_bot_om_JNISolutionVerifier
 * Method:    getHeight
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_faendir_zachtronics_bot_om_JNISolutionVerifier_getHeight
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_faendir_zachtronics_bot_om_JNISolutionVerifier
 * Method:    getWidth
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_faendir_zachtronics_bot_om_JNISolutionVerifier_getWidth
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
