/*
 * Copyright (c) 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.faendir.zachtronics.bot.mors

import net.bramp.ffmpeg.FFprobe
import net.bramp.ffmpeg.probe.FFmpegProbeResult
import net.bramp.ffmpeg.shared.CodecType
import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import java.io.File

/**
 * Validates that uploaded GIFs match the Opus Magnum game recorder output.
 */
@Service
class GifValidationService(private val ffprobe: FFprobe = FFprobe()) {

    companion object {
        private val logger = LoggerFactory.getLogger(GifValidationService::class.java)

        private const val INVALID_GIF_MESSAGE = "Please submit a valid GIF generated by the Opus Magnum game."

        private const val MIN_GIF_SIZE = 10 * 1024   // 10 KB
        private const val MIN_DURATION_SECS = 0.1
        private const val MIN_WIDTH = 500
        private const val MIN_HEIGHT = 400
    }

    /**
     * Validates the GIF before upload:
     * - minimum file size (10 KB)
     * - minimum duration (0.1s)
     * - reasonable dimensions (at least 500x400, landscape orientation)
     */
    fun validate(gif: ByteArray) {
        if (gif.size < MIN_GIF_SIZE) {
            logger.debug("GIF rejected: too small ({} bytes)", gif.size)
            throw IllegalArgumentException(INVALID_GIF_MESSAGE)
        }

        val probe = probe(gif)
        val format = probe.format
        val stream = probe.streams?.firstOrNull { it.codec_type == CodecType.VIDEO }

        if (format == null || stream == null) {
            logger.debug("GIF rejected: missing format or video stream")
            throw IllegalArgumentException(INVALID_GIF_MESSAGE)
        }

        if (format.duration < MIN_DURATION_SECS) {
            logger.debug("GIF rejected: duration too short ({}s)", format.duration)
            throw IllegalArgumentException(INVALID_GIF_MESSAGE)
        }
        if (stream.width < MIN_WIDTH || stream.height < MIN_HEIGHT) {
            logger.debug("GIF rejected: dimensions too small ({}x{})", stream.width, stream.height)
            throw IllegalArgumentException(INVALID_GIF_MESSAGE)
        }
        if (stream.width < stream.height) {
            logger.debug("GIF rejected: not landscape ({}x{})", stream.width, stream.height)
            throw IllegalArgumentException(INVALID_GIF_MESSAGE)
        }
    }

    private fun probe(gif: ByteArray): FFmpegProbeResult {
        val tempFile = File.createTempFile("probe", ".gif")
        try {
            tempFile.writeBytes(gif)
            return ffprobe.probe(tempFile.absolutePath)
        } catch (e: Exception) {
            logger.warn("Failed to probe GIF", e)
            throw IllegalArgumentException(INVALID_GIF_MESSAGE, e)
        } finally {
            tempFile.delete()
        }
    }
}
