/*
 * Copyright (c) 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.faendir.zachtronics.bot.mors

import org.junit.jupiter.api.Test
import org.springframework.core.io.ClassPathResource
import strikt.api.expectCatching
import strikt.api.expectThrows
import strikt.assertions.isEqualTo
import strikt.assertions.isSuccess
import strikt.assertions.message

internal class GifValidationServiceTest {

    private val gifValidationService = GifValidationService()

    @Test
    fun `valid GIF passes validation`() {
        val gif = ClassPathResource("Face_Powder_Height_1.gif").file.readBytes()
        expectCatching { gifValidationService.validate(gif) }.isSuccess()
    }

    @Test
    fun `GIF smaller than minimum size is rejected`() {
        expectThrows<IllegalArgumentException> { gifValidationService.validate(ByteArray(100)) }
            .message.isEqualTo("Please submit a valid GIF generated by the Opus Magnum game.")
    }

    @Test
    fun `GIF with too short duration is rejected`() {
        val gif = ClassPathResource("gif_short_duration.gif").file.readBytes()
        expectThrows<IllegalArgumentException> { gifValidationService.validate(gif) }
            .message.isEqualTo("Please submit a valid GIF generated by the Opus Magnum game.")
    }

    @Test
    fun `GIF with wrong dimensions is rejected`() {
        val gif = ClassPathResource("gif_wrong_dimensions.gif").file.readBytes()
        expectThrows<IllegalArgumentException> { gifValidationService.validate(gif) }
            .message.isEqualTo("Please submit a valid GIF generated by the Opus Magnum game.")
    }
}
