/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_faendir_zachtronics_bot_om_JNISolutionVerifier */

#ifndef _Included_com_faendir_zachtronics_bot_om_JNISolutionVerifier
#define _Included_com_faendir_zachtronics_bot_om_JNISolutionVerifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_faendir_zachtronics_bot_om_JNISolutionVerifier
 * Method:    prepareVerifier
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_faendir_zachtronics_bot_om_JNISolutionVerifier_prepareVerifier
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_faendir_zachtronics_bot_om_JNISolutionVerifier
 * Method:    closeVerifier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_faendir_zachtronics_bot_om_JNISolutionVerifier_closeVerifier
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_faendir_zachtronics_bot_om_JNISolutionVerifier
 * Method:    getMetric
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_faendir_zachtronics_bot_om_JNISolutionVerifier_getMetric
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
