name: Renovate
on:
  schedule:
    - cron: '0 12 * * SAT'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Renovate
        uses: renovatebot/github-action@v29.32.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}